### ISSUE TITLE
Strong name package

### ISSUE THREAD

**Issue by vadimi** [maxhauser/semver#22] opened 2016-09-14 17:12 UTC
I'd like to use that library, but all projects in my solution are strong named. Any chance we can get a strong name version of the package? Maybe something similar to Dapper: 

[https://www.nuget.org/packages/Dapper.StrongName/](https://www.nuget.org/packages/Dapper.StrongName/)

**Comment by Sam13** [comment] 2016-11-15 15:29
+1

**Comment by WalkerCodeRanger** [comment] 2019-10-12 04:05
Closing this as a duplicate of issue #23

**Closed by WalkerCodeRanger** 2019-10-12 04:05 UTC
Labels: duplicate, enhancement
