### ISSUE TITLE
SemVersion.Parse throws System.OverflowException

### ISSUE THREAD

**Issue by WenceyWang** [maxhauser/semver#74] opened 2022-12-12 14:51 UTC
By running
```
SemVersion.Parse( "0.0.0-202110100305", SemVersionStyles.Any )
```
Will throw exception
```
System.OverflowException: 'Prerelease identifier '202110100305' was too large for Int32 in version '0.0.0-202110100305'.'
```
with
```
<PackageReference Include="semver" Version="2.3.0-alpha.0" />
```
on dotnet 7.

**Comment by WalkerCodeRanger** [comment] 2022-12-13 04:04
Closing this as a duplicate of #73 "System.OverflowException: 'Prerelease identifier 'xxx' was too large for Int32 in version 'xxx'.' #73". As I said in that ticket:
>The semver spec does not give an upper limit to numeric prerelease identifiers nor for the major, minor, or patch. However, for ease of developer use `int` was used for these. It was thought unlikely people would run into those limits. For v3.0 of the library, we can consider using `long` or `BigInteger`.

>In the mean time, I would suggest turning it into an alphanumeric prerelease identifier following the ISO 8601 standard (e.g. `1.0.0-2022-08-28.1200`) or dot separating each of the parts (e.g. `1.0.0-2022.08.28.1200`)

**Closed by WalkerCodeRanger** 2022-12-13 04:04 UTC
